Player 1 Input:
  Handler: Evdev
  Device: Microsoft X-Box 360 pad
  Profile: Default Profile
Player 2 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile
Player 3 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile
Player 4 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile
Player 5 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile
Player 6 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile
Player 7 Input:
  Handler: "Null"
  Device: "Null"
  Profile: Default Profile